-- task table
insert into task(id, src, algo, status, description) values (1, 'file:///home/ivan/git/demo-djt/files/file1', 'md5', 'NEW', null)
insert into task(id, src, algo, status, description) values (2, 'file:///home/ivan/git/demo-djt/files/file2', 'sha-1', 'NEW', null)
insert into task(id, src, algo, status, description) values (3, 'file:///home/ivan/git/demo-djt/files/file3', 'md5', 'SUCCESS', 'Task has been done')
insert into task(id, src, algo, status, description) values (4, 'file:///home/ivan/git/demo-djt/files/file4', 'sha-1', 'NEW', null)
insert into task(id, src, algo, status, description) values (5, 'file:///home/ivan/git/demo-djt/files/file5', 'sha-256', 'NEW', null)
insert into task(id, src, algo, status, description) values (6, 'file:///home/ivan/git/demo-djt/files/file6', 'md5', 'FAILURE', 'Error: java.lang.OutOfMemoryError: Java heap space')
insert into task(id, src, algo, status, description) values (7, 'file:///home/ivan/git/demo-djt/files/file7', 'sha-256', 'NEW', null)
insert into task(id, src, algo, status, description) values (8, 'file:///home/ivan/git/demo-djt/files/file8', 'sha-256', 'NEW', null)
insert into task(id, src, algo, status, description) values (9, 'file:///home/ivan/git/demo-djt/files/file9', 'md5', 'NEW', null)
insert into task(id, src, algo, status, description) values (10, 'file:///home/ivan/git/demo-djt/files/file10', 'sha-1', 'NEW', null)
insert into task(id, src, algo, status, description) values (11, 'file:///home/ivan/git/demo-djt/files/file11', 'md5', 'NEW', null)
insert into task(id, src, algo, status, description) values (12, 'file:///home/ivan/git/demo-djt/files/file12', 'sha-256', 'SUCCESS', 'Task has been done')
insert into task(id, src, algo, status, description) values (13, 'file:///home/ivan/git/demo-djt/files/file13', 'sha-1', 'FAILURE', 'Error: java.lang.OutOfMemoryError')
insert into task(id, src, algo, status, description) values (14, 'file:///home/ivan/git/demo-djt/files/file14', 'sha-1', 'NEW', null)
insert into task(id, src, algo, status, description) values (15, 'file:///home/ivan/git/demo-djt/files/file15', 'sha-256', 'NEW', null)